package Oct.Practice;

import java.util.Scanner;

//🎯 How To Explain This in Interview (Best Version)
//
//Say this confidently:
//
//    "The Fibonacci sequence is generated by adding the previous two numbers.
//     I initialize the first two values as 0 and 1. In each iteration, I print the current number,
//     calculate the next number as the sum of the previous two, and then shift the values forward.
//     The time complexity is O(n) and space complexity is O(1) because only constant variables are used."
//
//That answer sounds structured and professional.

public class Ex26_Fibonacci_Series {

    public static void main(String[] args) {

        // Creating Scanner object to take input from user
        Scanner sc = new Scanner(System.in);

        // Asking user to enter number of terms
        System.out.print("Enter a number: ");

        // Reading input and storing it in variable 'num'
        int num = sc.nextInt();

        // Checking if input is invalid (Fibonacci cannot be generated for <= 0)
        if (num < 1) {
            System.out.println("Please enter a positive number");
            return;  // Stop execution if input is invalid
        }

        // Initializing first two Fibonacci numbers
        int first = 0;
        int second = 1;

        // Loop runs (num - 1) times to generate series
        for (int i = 1; i < num; i++) {

            // Printing current Fibonacci number
            System.out.print(first + " ");

            // Calculating next number in sequence
            int next = first + second;

            // Updating values (shifting mechanism)
            first = second;
            second = next;
        }

        sc.close();  // Closing scanner resource
    }
}

